// Script to convert Excel file to JSON
// Run this once to generate student data from ANNEX FIRST FLOOR.xlsx

import XLSX from 'xlsx';
import fs from 'fs';

// Read the Excel file
const workbook = XLSX.readFile('ANNEX FIRST FLOOR.xlsx');
const sheetName = workbook.SheetNames[0];
const worksheet = workbook.Sheets[sheetName];

// Convert to array of arrays (since the Excel doesn't have proper headers)
const data = XLSX.utils.sheet_to_json(worksheet, { header: 1 });

console.log(`📊 Total rows in Excel: ${data.length}`);

// Create a lookup object by registration number
const studentLookup = {};
let successCount = 0;
let skipCount = 0;

data.forEach((row, index) => {
    // Skip empty rows
    if (!row || row.length === 0) {
        skipCount++;
        return;
    }

    // Expected format: [Room, RegNo, Name]
    const room = row[0];
    const regNo = row[1];
    const name = row[2];

    // Only add if we have both regNo and name
    if (regNo && name) {
        const regNoStr = regNo.toString().trim();
        const nameStr = name.toString().trim();
        const roomStr = room ? room.toString().trim() : '';

        studentLookup[regNoStr] = {
            name: nameStr,
            room: roomStr
        };
        successCount++;

        // Log first few entries for verification
        if (successCount <= 5) {
            console.log(`✅ Added: ${regNoStr} -> ${nameStr} (Room: ${roomStr})`);
        }
    } else {
        skipCount++;
    }
});

console.log(`\n📈 Summary:`);
console.log(`   ✅ Successfully added: ${successCount} students`);
console.log(`   ⏭️  Skipped: ${skipCount} rows (empty or invalid)`);

// Write to JSON file
fs.writeFileSync(
    'src/data/students.json',
    JSON.stringify(studentLookup, null, 2)
);

// Also update the students.js file
const jsContent = `// Student data lookup - Auto-populated from ANNEX FIRST FLOOR
// This file was auto-generated by convert-excel.js on ${new Date().toLocaleString()}
// Total students: ${successCount}

export const studentData = ${JSON.stringify(studentLookup, null, 4)};

// Function to get student info by registration number
export const getStudentInfo = (regNo) => {
    if (!regNo) return null;

    // Normalize the registration number (remove spaces, convert to uppercase)
    const normalizedRegNo = regNo.toString().trim().toUpperCase();

    // Try exact match first
    if (studentData[normalizedRegNo]) {
        return studentData[normalizedRegNo];
    }

    // Try case-insensitive match
    const key = Object.keys(studentData).find(
        k => k.toUpperCase() === normalizedRegNo
    );

    return key ? studentData[key] : null;
};
`;

fs.writeFileSync('src/data/students.js', jsContent);

console.log(`\n✅ Files generated successfully!`);
console.log(`   📄 src/data/students.json`);
console.log(`   📄 src/data/students.js`);
console.log(`\n🔍 Sample lookup test:`);
console.log(`   25013635 ->`, studentLookup['25013635'] || 'NOT FOUND');
